Move black linting to main script

diff --git a/.github/workflows/doc-lint-test.yaml b/.github/workflows/doc-lint-test.yaml
--- a/.github/workflows/doc-lint-test.yaml
+++ b/.github/workflows/doc-lint-test.yaml
@@ -251,3 +251,30 @@ jobs:
             echo "::error::due to flake8 violations, return code ${ret}"
             exit 1
           fi
+
+  lint_black:
+    runs-on: ${{ vars.RUNNER }}
+    needs: build_doclinttest_image
+    container:
+      image: ${{ needs.build_doclinttest_image.outputs.IMAGE_NAME }}:${{ github.sha }}
+      credentials:
+        username: ${{ secrets.GHCR_USER }}
+        password: ${{ secrets.GHCR_TOKEN }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run code check script black
+        shell: bash -l {0}
+        run: |
+          echo "::group::black_analysis"
+          echo "BLACK analysis of code"
+          black --version
+          ./tests/utils/check_code.sh black ./
+          ret=$?
+          echo "Return code: ${ret}"
+          echo "::endgroup::"
+          if [[ "${ret}" != *"0"* ]]; then
+            echo "::error::due to black violations, return code ${ret}"
+            exit 1
+          fi
