Add flake8

diff --git a/.github/workflows/doc-lint-test.yaml b/.github/workflows/doc-lint-test.yaml
--- a/.github/workflows/doc-lint-test.yaml
+++ b/.github/workflows/doc-lint-test.yaml
@@ -188,10 +188,6 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      # - name: Configure Git safe directory
-      #   run: git config --global --add safe.directory $PWD
-
       - name: Run bandit
         shell: bash -l {0}
         run: |
@@ -228,5 +224,30 @@ jobs:
           echo "::endgroup::"
           if [[ "${ret}" != *"0"* ]]; then
             echo "::error::due to doc8 violations, return code ${ret}"
+            exit 1
+          fi
+
+  lint_flake8:
+    runs-on: ${{ vars.RUNNER }}
+    needs: build_doclinttest_image
+    container:
+      image: ${{ needs.build_doclinttest_image.outputs.IMAGE_NAME }}:${{ github.sha }}
+      credentials:
+        username: ${{ secrets.GHCR_USER }}
+        password: ${{ secrets.GHCR_TOKEN }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Run flake8
+        shell: bash -l {0}
+        run: |
+          echo "::group::flake8_analysis"
+          echo "FLAKE8 analysis of code"
+          ./geoips_default_branch/tests/utils/check_code.sh flake8 .
+          ret=$?
+          echo "Return code: ${ret}"
+          echo "::endgroup::"
+          if [[ "${ret}" != *"0"* ]]; then
+            echo "::error::due to flake8 violations, return code ${ret}"
             exit 1
           fi
