Fix release file check

diff --git a/.github/workflows/doc-lint-test.yaml b/.github/workflows/doc-lint-test.yaml
--- a/.github/workflows/doc-lint-test.yaml
+++ b/.github/workflows/doc-lint-test.yaml
@@ -231,24 +231,23 @@ jobs:
       - name: Detect new and modified release files
         run: |
           update_this_file="$(cat $BASE_GEOIPS_PATH/update_this_release_note)"
-          release_notes_dir="$(dirname $update_this_file)/$(basename $update_this_file .rst)"
-          echo "Release Note Dir is $release_notes_dir which contains"
-          ls -l $release_notes_dir
-          current_release_note=`cat $PWD/geoips_default_branch/update_this_release_note`
-          echo "git -C $PWD/geoips_plugin_repo diff --name-only --diff-filter=AM ${COMMIT_INTO} -- $release_notes_dir/*.yaml"
-          ret=$(git -C $PWD/geoips_plugin_repo diff --name-only --diff-filter=AM ${COMMIT_INTO} -- $release_notes_dir/*.yaml)
+          release_notes_dir="$BASE_GEOIPS_PATH/$(dirname $update_this_file)/$(basename $update_this_file .rst)"
+          ls $release_notes_dir
+          current_release_note=`cat $BASE_GEOIPS_PATH/update_this_release_note`
+          echo "git -C $BASE_GEOIPS_PATH diff --name-only --diff-filter=AM remotes/origin/main -- $release_notes_dir/*.yaml"
+          ret=$(git -C $BASE_GEOIPS_PATH diff --name-only --diff-filter=AM remotes/origin/main -- $release_notes_dir/*.yaml)
 
           echo "Release note files modified this PR:"
           for file in ${ret[@]}; do
               echo "    $file"
           done
-          #if [[ "${ret}" != *"$current_release_note"* ]]; then
-          #    echo "FAILED: No release note changes detected"
-          #    echo "Please enter change logs in $current_release_note"
-          #    exit 1
-          #else
-          #    echo "PASSED"
-          #fi
+          if [ ${#errors[@]} -eq 0 ]; then
+              echo "FAILED: No release note changes detected"
+              echo "Please use brassy to enter change logs in $release_notes_dir"
+              exit 1
+          else
+              echo "PASSED"
+          fi
 
       - name: Build release notes from yaml files
         id: release-note-generator
